---

- name: Install package
  become: True
  package:
    name: eth-netcenter-api
    state: present

- name: Configure package
  become: True
  template:
    src: dnsapi.properties.j2
    dest: /etc/dnsapi.properties
    owner: dnsapi
    group: dnsapi
    mode: 0600
  notify: Restart service

- name: Start service
  become: True
  service:
    name: dns-api
    state: started
    enabled: True
